import React from 'react'; // Import React for rendering JSX
// Import rich charts utilities from recharts library to build beautiful CRM analytics
import { 
  LineChart,        // Area/Line container
  Line,             // Line path element
  BarChart,         // Columns bar container
  Bar,              // Bar columns element
  Cell,             // Individual cell customization
  XAxis,            // Horizontal axis
  YAxis,            // Vertical axis
  CartesianGrid,    // Background grids lines
  Tooltip,          // Hover value indicator card
  Legend,           // Description index mapping
  ResponsiveContainer // Responsiveness wrapper
} from 'recharts';
// Import sleek graphic icons from lucide-react library
import { 
  BarChart2,   // Chart icon
  PieChart,    // Pie icon
  DollarSign,  // Revenue symbol
  TrendingUp,  // Uplift arrow icon
  ArrowUpRight // Small trend arrow
} from 'lucide-react';

// Monthly target vs actual closed revenue data
const revenuePerformanceTrend = [
  { month: 'Jan', ClosedRevenue: 32000, Target: 30000 }, // January
  { month: 'Feb', ClosedRevenue: 48000, Target: 35000 }, // February
  { month: 'Mar', ClosedRevenue: 42000, Target: 40000 }, // March
  { month: 'Apr', ClosedRevenue: 58000, Target: 45000 }, // April
  { month: 'May', ClosedRevenue: 72000, Target: 55000 }, // May
  { month: 'Jun', ClosedRevenue: 98000, Target: 70000 }  // June
];

// Distribution of lead quantities generated by channel source
const leadChannelsSpread = [
  { source: 'LinkedIn', Count: 480, color: '#3B82F6' },       // LinkedIn: Blue
  { source: 'Direct Search', Count: 340, color: '#10B981' },  // Web/Direct: Emerald
  { source: 'Email Outbound', Count: 280, color: '#F59E0B' }, // Outbound: Yellow
  { source: 'Referrals', Count: 190, color: '#8B5CF6' },      // Referrals: Purple
  { source: 'Partnerships', Count: 120, color: '#EC4899' }    // Partners: Pink
];

// Funnel stages attrition rate count mapping
const salesStageAttritionFunnel = [
  { stage: 'Leads Created', Volume: 1400 }, // Initial Lead creation
  { stage: 'Contacted', Volume: 1050 },     // Outreached
  { stage: 'Qualified', Volume: 780 },      // Passed qualification
  { stage: 'Proposal Sent', Volume: 450 },  // Offer sent
  { stage: 'Negotiation', Volume: 280 },    // Active negotiation
  { stage: 'Deals Won', Volume: 168 }       // Closed won deals
];

const Analytics = () => {
  return (
    // Outer stack layout with spacing gap
    <div className="flex flex-col gap-8">
      
      {/* Top statistics summary row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* Metric 1: Customer Acquisition Cost (CAC) */}
        <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-sm">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Customer Acquisition Cost</p>
          <div className="flex items-baseline gap-2 mt-2">
            <h4 className="text-2xl font-bold text-white">$142</h4>
            <span className="text-xs font-medium text-emerald-400 flex items-center gap-0.5">
              <TrendingUp className="w-3 h-3" />
              -11.2% YoY
            </span>
          </div>
          <p className="text-[10px] text-slate-500 mt-2">Cost to acquire a customer has dropped due to high referral rates</p>
        </div>

        {/* Metric 2: Customer Lifetime Value (LTV) */}
        <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-sm">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Customer Lifetime Value</p>
          <div className="flex items-baseline gap-2 mt-2">
            <h4 className="text-2xl font-bold text-white">$8,600</h4>
            <span className="text-xs font-medium text-emerald-400 flex items-center gap-0.5">
              <TrendingUp className="w-3 h-3" />
              +5.4% YoY
            </span>
          </div>
          <p className="text-[10px] text-slate-500 mt-2">Calculated over a rolling 12-month customer lifespan average</p>
        </div>

        {/* Metric 3: LTV : CAC Ratio */}
        <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-sm">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">LTV : CAC Ratio</p>
          <div className="flex items-baseline gap-2 mt-2">
            <h4 className="text-2xl font-bold text-white">60.5x</h4>
            <span className="text-xs font-medium text-emerald-400 flex items-center gap-0.5">
              <TrendingUp className="w-3 h-3" />
              +14.7% YoY
            </span>
          </div>
          <p className="text-[10px] text-slate-500 mt-2">Health benchmark multiplier is 3.0x. Startup performance is elite</p>
        </div>

      </div>

      {/* Analytics Chart Row 1: Line chart for Revenue trends (Full Width) */}
      <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-md">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h4 className="text-base font-bold text-white tracking-wide">Revenue Performance vs Target</h4>
            <p className="text-xs text-slate-500 mt-1">Comparing target thresholds against actual closed deal values in USD</p>
          </div>
          {/* Legend indicators */}
          <div className="flex gap-4 text-xs font-semibold text-slate-400">
            <div className="flex items-center gap-1.5">
              <span className="w-3 h-0.5 bg-blue-500 inline-block"></span>
              <span>Closed Revenue</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="w-3 h-0.5 bg-slate-600 inline-block border-dashed border"></span>
              <span>Target</span>
            </div>
          </div>
        </div>

        {/* Chart Viewport container */}
        <div className="h-80 mt-6 w-full text-xs">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={revenuePerformanceTrend} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1E293B" vertical={false} />
              <XAxis dataKey="month" stroke="#64748B" tickLine={false} axisLine={false} />
              <YAxis stroke="#64748B" tickLine={false} axisLine={false} tickFormatter={(val) => `$${val/1000}k`} />
              <Tooltip 
                contentStyle={{ 
                  backgroundColor: '#0F172A', 
                  borderColor: '#1E293B', 
                  borderRadius: '12px',
                  color: '#F1F5F9'
                }} 
                formatter={(value) => [`$${value.toLocaleString()}`, '']}
              />
              {/* Actual line (solid Blue) */}
              <Line type="monotone" dataKey="ClosedRevenue" stroke="#3B82F6" strokeWidth={3} dot={{ r: 4, strokeWidth: 2, stroke: '#0F172A' }} activeDot={{ r: 6 }} />
              {/* Target line (dashed gray) */}
              <Line type="monotone" dataKey="Target" stroke="#64748B" strokeWidth={2} strokeDasharray="5 5" dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Analytics Chart Row 2: Splits into two columns (Bar charts of sources and funnel attrition table) */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Column 1: Lead acquisition channels Bar chart */}
        <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-md">
          <div>
            <h4 className="text-base font-bold text-white tracking-wide">Acquisition Channels Spread</h4>
            <p className="text-xs text-slate-500 mt-1">Total leads captured split by specific channel source</p>
          </div>

          <div className="h-72 mt-6 w-full text-xs">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={leadChannelsSpread} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1E293B" vertical={false} />
                <XAxis dataKey="source" stroke="#64748B" tickLine={false} axisLine={false} />
                <YAxis stroke="#64748B" tickLine={false} axisLine={false} />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: '#0F172A', 
                    borderColor: '#1E293B', 
                    borderRadius: '12px',
                    color: '#F1F5F9'
                  }} 
                  cursor={{ fill: '#1E293B', opacity: 0.2 }}
                />
                {/* Colored bars mapping source attributes */}
                <Bar dataKey="Count" radius={[6, 6, 0, 0]}>
                  {leadChannelsSpread.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Column 2: Attrition funnel visual stats */}
        <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-md flex flex-col justify-between">
          <div>
            <h4 className="text-base font-bold text-white tracking-wide">Pipeline Conversion Funnel</h4>
            <p className="text-xs text-slate-500 mt-1">Tracking lead volumes at successive lifecycle milestones</p>
          </div>

          {/* Attrition stages bars */}
          <div className="mt-6 space-y-4">
            {salesStageAttritionFunnel.map((item, index) => {
              // Calculate width ratio relative to the largest value in the funnel list
              const widthRatio = (item.Volume / salesStageAttritionFunnel[0].Volume) * 100;
              return (
                <div key={item.stage} className="space-y-1.5">
                  <div className="flex justify-between items-center text-xs font-semibold">
                    <span className="text-slate-400">{item.stage}</span> {/* Funnel label */}
                    <span className="text-slate-200">
                      {item.Volume.toLocaleString()} <span className="text-slate-500 text-[10px]">({Math.round(widthRatio)}%)</span>
                    </span>
                  </div>
                  {/* Progress bar visual container */}
                  <div className="h-2 w-full bg-slate-950 rounded-full overflow-hidden border border-slate-900/60">
                    <div 
                      style={{ width: `${widthRatio}%` }} // Dynamic width inline styling
                      className="h-full bg-gradient-to-r from-blue-600 to-indigo-500 rounded-full transition-all duration-500"
                    ></div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

      </div>

    </div>
  );
};

export default Analytics; // Export Analytics Page component
